---
title: "2022-02-15 #DuBoisChallenge2022"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(extrafont)
library(cdlTools)
library(usmap)

# font_import()
loadfonts(device = "win")

`%nin%` = Negate(`%in%`)

font <- "Lucida Sans"

```



# challenge_03 Map

```{r}
dat2020 <- read_csv("data2020.csv") |>  janitor::clean_names()
```
## Make bins

* This split gives a somewhat even distribution of states into bins

```{r}
dat_binned <- dat2020 |> 
  mutate(bin = case_when(percent_of_labor_force <=36 & percent_of_labor_force > 30 ~ "30 - 36 %",
                         percent_of_labor_force <=30 & percent_of_labor_force > 20 ~ "20 - 30 %",
                         percent_of_labor_force <=20 & percent_of_labor_force > 15 ~ "15 - 20 %",
                         percent_of_labor_force <=15 & percent_of_labor_force > 10 ~ "10 - 15 %",
                         percent_of_labor_force <=10 & percent_of_labor_force > 7.5 ~ "7.5 - 10 %",
                         percent_of_labor_force <=7.5 & percent_of_labor_force > 5 ~ "5 - 7.5 %",
                         percent_of_labor_force <=5 & percent_of_labor_force > 2.5 ~ "2.5 - 5 %",
                         percent_of_labor_force <=2.5& percent_of_labor_force > 0 ~ "0 - 2.5 %"),
         bin = fct_relevel(bin, levels = c("30 - 36 %","20 - 30 %",  
                                      "15 - 20 %", "10 - 15 %",
                                      "7.5 - 10 %", "5 - 7.5 %",
                                      "2.5 - 5 %", "0 - 2.5 %")),
         fips = fips(state))


```

```{r}
basic_map_gg <- plot_usmap(data = dat_binned, regions = "states", values = "bin")
```


```{r}
basic_map_gg +
  theme_panel_03
```


### Building theme

```{r}
theme_challenge_04 <- theme(legend.position = "none",
      axis.title.y=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks.y=element_blank(),
      axis.ticks.x=element_blank(),
      axis.title.x = element_blank(),
      plot.title = element_text(hjust = 0.5, family = font, size = 11.5),
      plot.subtitle = element_text(hjust = 0.5, family = font, size = 9),
      panel.border = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.grid = element_line(), 
      panel.background = element_rect(fill = "#dccec2", color = "#dccec2"),
      plot.background = element_rect(fill = "#dccec2", color = "#dccec2"),
      axis.text.x=element_text(face = "bold", family = font, size =14, color = "#101010")) 
```

```{r}
theme_panel_03 <- theme(legend.position = "none",
      axis.title.y=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks.y=element_blank(),
      axis.ticks.x=element_blank(),
      axis.title.x = element_blank(),
      plot.title = element_text(hjust = 0.5, family = font, size = 11.5),
      plot.subtitle = element_text(hjust = 0.5, family = font, size = 9),
      panel.border = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.grid = element_line(), 
      panel.background = element_rect(fill = "#dccec2", color = "#dccec2"),
      plot.background = element_rect(fill = "#dccec2", color = "#dccec2"),
      axis.text.x=element_text(face = "bold", family = font, size =14, color = "#101010")) 
```

```{r}
title_03 = "PERCENT OF EACH STATE'S LABOR FORCE THAT IS AFRICAN AMERICAN, 2020 ANNUAL AVERAGES"
subtitle_03 = "Data = U.S. BUREAU OF LABOR STATISTICS"
```


```{r fig1, fig.height = 10, fig.width = 8, fig.align = "center"}
p <- freed_slaves_long %>% 
  ggplot(aes(x = Year, y = Percentage, color = Status, fill = Status)) +
  geom_col(width = 10) + 
  scale_x_continuous(breaks = c(unique(freed_slaves$Year)), position= "top") + 
  labs(title = "PROPORTION OF FREEMEN AND SLAVES AMONG AMERICAN NEGROES  .\n\n\nPROPORTION DES NÈGRES LIBRES ET DES ESCLAVES EN AMÉRIQUE  .\n\n", 
       subtitle = "DONE BY ATLANTA UNIVERSITY .\n\n\n")+
  theme_challenge_04 +
  scale_fill_manual(values=c("#4e996f", "#101010")) +
  scale_color_manual(values=c("#4e996f", "#101010")) +
  annotate("text", label = "SLAVES\nESCLAVES", x = 1828, y = 50, 
           color = "#dccec2", family = font, size = 7) +
  annotate("text", label = "FREE - LIBRE", x = 1828, y = 95, 
           color = "#101010", family = font, size = 5.5) +
  geom_text(data = freed_slaves_long %>%  filter(Year != 1870), 
            aes(label = paste0(Percentage, "%"), y = 102-Percentage), 
            color = "#101010", family = font) +
  annotate("text", label = "100 %", x = 1870, y = 92, 
           color = "#101010", family = font, size = 4)

p
```


### Second thoughts

* Better approach would be using geom_smooth for either free or slave category and fill the background either green or black

```{r fig2, fig.height = 10, fig.width = 8, fig.align = "center"}
p2 <- ggplot(data = freed_slaves, aes(x = Year, y = Slave)) +
  geom_rect(aes(xmin = 1790, xmax = 1870, ymin = 1, ymax = 100), color = "#4e996f", fill = "#4e996f") +
  geom_ribbon( aes(ymin = 0,ymax = predict(loess(Slave ~ Year, span = 0.4))),
               alpha = 1,fill = "#101010") +
  geom_linerange(data = freed_slaves %>%  filter(Year %nin% c(1790, 1870)),aes(x = Year, ymin = predict(loess(Slave ~ Year, span = 0.4)) +3, ymax = 100), color ="#101010", fill = "#101010", width = 0.1) +
  scale_x_continuous(breaks = c(unique(freed_slaves$Year)), limits = c(1790, 1870), position= "top") + 
  labs(title = "PROPORTION OF FREEMEN AND SLAVES AMONG AMERICAN NEGROES  .\n\n\nPROPORTION DES NÈGRES LIBRES ET DES ESCLAVES EN AMÉRIQUE  .\n\n", 
       subtitle = "DONE BY ATLANTA UNIVERSITY .\n\n\n")+
  theme_challenge_04 +
  annotate("text", label = "SLAVES\nESCLAVES", x = 1830, y = 55, 
           color = "#dccec2", family = font, size = 7.5) +
  annotate("text", label = "FREE - LIBRE", x = 1830, y = 97, 
           color = "#101010", family = font, size = 5.5) +
  geom_text(data = freed_slaves_long %>%  filter(Year %nin% c(1790, 1870)),
            aes(label = paste0(Percentage, "%"), y = 102-Percentage),
            color = "#101010", family = font) +
  annotate("text", label = "100 %", x = 1870, y = 92,
           color = "#101010", family = font, size = 4) +
  annotate("text", label = "8 %", x = 1790, y = 94,
           color = "#101010", family = font, size = 4) 



p2
```

### Notes
* Needs better font
* x-axis label should be moved down

```{r}
ggsave(p2, filename = "challenge_04.png", units = "cm", width = 12, height = 16, limitsize = F, scale = 1.4)
```

```{r}
sessionInfo()
```


















