---
title: "2023-05-23 Central Park Squirrels"
author: Florian Tanner
date: "`r format(Sys.time())`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())

library(tidyverse)
library(ggtext)
library(ggrepel)
library(png)
library(patchwork)
library(showtext)
sysfonts::font_add_google("Roboto Condensed")
showtext::showtext_auto()
showtext::showtext_opts(dpi = 300)
```

```{r}
squirrel_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-05-23/squirrel_data.csv') 

squirrel_data_clean <- squirrel_data%>% 
  janitor::clean_names()%>% 
  mutate(date = as.Date(as.character(date), format = '%m%d%Y' ))
```

```{r}
squirrel_data_clean%>% skimr::skim()
```

## Notes

Find clusters 

## Choose predictor variables (Based on NAs and relevance for clustering)

```{r}
id_cols <- "unique_squirrel_id"
pred_cols <- c("age", "combination_of_primary_and_highlight_color", "x", "y", "hectare_squirrel_number" )

cluster_dat <- squirrel_data_clean %>% 
  select(id_cols, pred_cols, where(is.logical))
```

# Cluster pipeline

```{r}

```





```{r}
sessionInfo()
```


















