---
title: "2022-08-23 CHIP dataset"
author: Florian Tanner
date: "`r format(Sys.time())`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())

library(tidyverse)
library(ggtext)
library(ggrepel)
library(png)
library(patchwork)
library(showtext)
sysfonts::font_add_google("Roboto Condensed")
showtext::showtext_auto()
showtext::showtext_opts(dpi = 300)
```

```{r}
chips_full <- read_csv("chip_dataset.csv") |> 
  janitor::clean_names()

nvidia_logo <- grid::rasterGrob(readPNG("nvidia_logo_crop.png"))
```

```{r}
data <- chips_full |> 
  filter(type == "GPU",
         vendor == "NVIDIA",
         str_detect(product, pattern = c("RTX | GTX|GT")),
         release_date != "NaT") |> 
  mutate(year = substr(release_date, 1, 4),
         product_line = case_when(str_detect(product, "GT") & 
                                    str_detect(product, "GTX", negate = T) &
                                    str_detect(product, "GTS", negate = T)
                                  ~ "GT",
                                  str_detect(product, "GTX") ~ "GTX",
                                  str_detect(product, "RTX ") ~ "RTX",
                                  TRUE ~ "other"),
         release_date = as.Date(release_date),
         product_label = str_remove(product, "NVIDIA "),
         product_label = str_remove(product_label, "GeForce "))
```


```{r}
theme_nvidia <- 
  theme_bw(base_size = 40, base_family = "Roboto Condensed") +
  theme(panel.background = element_rect(fill = "#76b900", color = "#76b900"),
        panel.grid = element_blank(),
        plot.background = element_rect(fill = "#76b900", color = "#76b900"),
        axis.title.x = element_text(family = "Roboto Condensed"),
        axis.title.y = element_text(family = "Roboto Condensed"),
        plot.title = element_blank(),
        plot.caption =element_textbox_simple(size = 22 ,lineheight = 1.2,
                                             padding = margin(5.5, 5.5, 5.5, 5.5),
                                             margin = margin(25, 0, 0, 0),
                                             maxheight = NULL),
        legend.position = "none") 

nvidia_scheme <- c("#F5F5F5", "#B3CAE7", "#7598C1")
```

```{r}
nvidia_title <- "FP32 GPU performance of <span style = 'color: #F5F5F5;font-weight:bold;'>GT</span>,<br><span style = 'color: #B3CAE7;font-weight:bold;'>GTX</span> and <span style = 'color: #7598C1;font-weight:bold;'>RTX</span> series has doubled<br>approximately every two years"

nvidia_caption <-  "Data: Sun, Yifan, et al. Summarizing CPU and GPU design trends with product data. arXiv preprint arXiv:1911.11313 (2019). | Graphic: @TannerFlorian"
```



```{r}
p <- data |> 
  filter(product_line != "other") |> 
  ggplot(aes(x = release_date, y = fp32_gflops, color = product_line )) +
  geom_point(color = "black", size = 3) +
  geom_point(size = 2.5) +
  ggrepel::geom_label_repel(aes(label=product_label, fill = product_line), color= "black", 
                            family = "Roboto Condensed") +
  scale_color_manual(values = nvidia_scheme) +
  scale_fill_manual(values = nvidia_scheme) +
  scale_x_date(limits = as.Date(c("2006-01-01", "2022-01-01"))) +
  scale_y_log10() +
  geom_richtext(aes(x = as.Date("2006-01-01"), y = 20000, label = nvidia_title),
                fill = NA, label.color = NA, size = 23, hjust = 0, color = "black",
                family = "Roboto Condensed", fontface= "bold", lineheight =1.3) +
  labs(y = "FP32 GFLOPS, log scale", x = "Release date", caption= nvidia_caption)



p <- p +
  inset_element(nvidia_logo, left = 0.7,
                bottom = 0.001,
                right = 0.99,
                top = 0.3) & theme_nvidia
```



```{r}
gt_gtx_rtx_gr <-data |> 
  filter(product_line != "other") |> 
  group_by(year) |> 
  summarise(mean_yearly_fp32_gflops = mean(fp32_gflops, na.rm = T)) |> 
  filter(is.numeric(mean_yearly_fp32_gflops)) |> 
  mutate(ann_growth = (lead(mean_yearly_fp32_gflops) - mean_yearly_fp32_gflops)/mean_yearly_fp32_gflops) |> 
  summarise(mean_gr = mean(ann_growth, na.rm = T)) |> 
  ungroup() |> 
  mutate(mean_doubling_time = log(2)/log(1+mean_gr))

```



```{r}
ggsave(plot = p, filename = "large.png", units = "cm", width = 60, height = 60, limitsize = F, device = "png")
```


```{r}
sessionInfo()
```


















