---
title: "2022-03-08 Erasmus student mobility"
author: Florian Tanner
date: "`r format(Sys.time())`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())

library(tidyverse)
library(showtext)
library(countrycode)
library(ggalluvial)

sysfonts::font_add_google("Poppins")
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)

font <- "Poppins"
```

```{r}
erasmus <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-08/erasmus.csv') 
iso<-read_delim("https://raw.githubusercontent.com/BjnNowak/TidyTuesday/main/data/iso.csv",delim=';')
```
```{r}
erasmus |> 
  count(mobility_duration)
```

# Dataset seems to be broken? 

```{r}
sankey_dat <- erasmus |> 
  filter(academic_year == "2018-2019") |> 
  group_by(sending_country_code, receiving_country_code) |> 
  summarize(participants = sum(participants)) |> 
  mutate(sending = countrycode(sending_country_code, origin = "iso2c", destination = "country.name"),
         receiving = countrycode(receiving_country_code, origin = "iso2c", destination = "country.name"))
```

```{r}
sankey_dat$sending[sankey_dat$sending_country_code == "EL"] <- "Greece"
sankey_dat$sending[sankey_dat$sending_country_code == "XK"] <- "Kosovo"
sankey_dat$sending[sankey_dat$sending_country_code == "UK"] <- "United Kingdom"

sankey_dat$receiving[sankey_dat$receiving_country_code == "EL"] <- "Greece"
sankey_dat$receiving[sankey_dat$receiving_country_code == "XK"] <- "Kosovo"
sankey_dat$receiving[sankey_dat$receiving_country_code == "UK"] <- "United Kingdom"
```

```{r}
sankey_dat_filtered <- sankey_dat |> 
  group_by(sending) |> 
  mutate(sending = case_when(participants < 20 ~ "Other",
                             participants >= 20 ~ sending)) |> 
  ungroup() |> 
  group_by(receiving) |> 
  mutate(receiving = case_when(participants < 20 ~ "Other",
                             participants >= 20 ~ receiving))
```


```{r, fig.height=10}
sankey_dat_filtered |> 
  filter(sending != receiving) |> # Not sure why this is necessary, seems like most participants stay in their own country?
  ggplot(aes(y= participants, axis1 = sending, axis2 = receiving )) +
  geom_alluvium(aes(fill = sending), width = 1/12) +
  geom_stratum(width = 1/12, fill = "black", color = "black", alpha = 0.3, lwd=2) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_void() +
  theme(legend.position = "none")
```
  
```{r}
sankey_dat_filtered |> 
  mutate(subject = seq(1, nrow(sankey_dat_filtered)))
```


```{r}
ggplot(vaccinations,
       aes(x = survey, stratum = response, alluvium = subject,
           y = freq,
           fill = response, label = response)) +
  scale_x_discrete(expand = c(.1, .1)) +
  geom_flow() +
  geom_stratum(alpha = .5) +
  geom_text(stat = "stratum", size = 3) +
  theme(legend.position = "none") +
  ggtitle("vaccination survey responses at three points in time")
```



```{r}
sessionInfo()
```


















