---
title: "2021-08-03 Paralympic Medals"
output: github_document
---

```{r setup, include=FALSE}
.libPaths("C:/R-packages2/")
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

```{r, message= FALSE, marning = FALSE, echo = FALSE}
library(tidyverse)
library(countrycode)
library(tidytext)
library(hrbrthemes)
extrafont::loadfonts(device = "win", quiet = TRUE)

`%nin%` <- Negate(`%in%`)
```

## Read data 

```{r}
athletes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-03/athletes.csv')
```

## Aim

Reproduce this graph by The Economist Graphic Detail
https://www.economist.com/graphic-detail/2021/07/25/which-is-the-strongest-olympic-team-of-all-time

## EDA Paralympics

* Why so many missing country names? 
* Need to manually add event locations


```{r}
skimr::skim(athletes)
```

```{r}
disciplines <- athletes %>% select(event) %>% distinct
disciplines
```

Observations:
* Data is for summer paralympics

## Summarise data

```{r}
country_medal_shares <- athletes %>% 
  filter(!is.na(abb)) %>% 
  group_by(abb, year) %>% 
  summarise(medal_count = n()) %>% 
  mutate(country_fill = countrycode(abb, origin= 'ioc', destination = 'country.name')) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  mutate(total_medals = sum(medal_count),
         medals_share = 100* medal_count/total_medals)

```
## Manually fill country_fill

```{r}
country_medal_shares$country_fill[country_medal_shares$abb == "URS"] <- "Soviet Union"
country_medal_shares$country_fill[country_medal_shares$abb == "SCG"] <- "Serbia and Montenegro"
country_medal_shares$country_fill[country_medal_shares$abb == "FRO"] <- "Faroe Islands"
country_medal_shares$country_fill[country_medal_shares$abb == "YUG"] <- "Yugoslavia"
country_medal_shares$country_fill[country_medal_shares$abb == "EUN"] <- "Unified Team"
country_medal_shares$country_fill[country_medal_shares$abb == "BIR"] <- "Burma"
country_medal_shares$country_fill[country_medal_shares$abb == "GDR"] <- "East Germany"
country_medal_shares$country_fill[country_medal_shares$abb == "TCH"] <- "Czechoslovakia"
country_medal_shares$country_fill[country_medal_shares$abb == "FRG"] <- "West Germany"
country_medal_shares$country_fill[country_medal_shares$abb == "IPP"] <- "Independent Paralympic Participants"
```


### Top teams



```{r}
top_three_per_year <- country_medal_shares %>% 
  mutate(country_fill = as.factor(country_fill)) %>% 
  group_by(year) %>% 
  slice_max(medals_share, n = 3)

```


Add grouping variable
```{r}
levels <- data.frame(levels = rep(c("3rd", "2nd", "1st"), 10))
top_three_per_year <- cbind(top_three_per_year, levels)
```


Host nations
```{r}
host_nations <- data.frame(year = seq(1980, 2016, 4), host = c("Netherlands", "United States", "South Korea", "Spain", "United States", "Australia", "Greece", "China", "United Kingdom", "Brazil"))

host_in_top <- top_three_per_year %>% 
  left_join(host_nations)

host_in_top$is_host_nation <- "no"
host_in_top$is_host_nation[host_in_top$country_fill == host_in_top$host] <- "yes"
```
Paralympics theme

```{r}
color_scheme2 <- c("#dfd9e2","#c3acce","#89909f","#538083","#2a7f62","#82d173","#4c2c69","#42253b","#084b83")

paralympics_theme <- theme_ipsum() +
  theme(
    legend.position = "none",
        axis.title.x  = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.x =  element_blank(),
        panel.grid.minor.x = element_blank())

label_family = "Arial Narrow"
```



```{r}
p <- host_in_top %>%
  ggplot(aes(x = year, 
             y = medals_share,
             fill = country_fill, 
             group = levels,
             color = is_host_nation)) +
  geom_col(position = position_stack(), size= 1, width=3.8) + 
  scale_color_manual(values = c("yes" = "black", "no" = "white")) +
  labs(title = "Home advantage?",
       subtitle = "Share of Paralympic medals won, top three teams at each summer games, %           \U25A1  Host nation",
       caption = "Data: International Paralympic Committee | Graphic: @TannerFlorian") +
  scale_fill_manual(values = color_scheme2) + 
  scale_x_continuous(breaks = seq(1980, 2016, 4)) +
  annotate(geom = "text", x = 2012, y = 9, label = "China", family= label_family, color = "white") + 
  annotate(geom = "text", x = 1992, y = 7, label = "Germany", family= label_family, color = "white") + 
  annotate(geom = "text", x = 1984, y = 7, label = "United\nStates", family= label_family) +
  annotate(geom = "text", x = 2000, y = 20, label = "France", family= label_family) +
  annotate(geom = "text", x = 1992, y = 29, label = "United\nKingdom", family= label_family) +
  annotate(geom = "text", x = 1988, y = 19, label = "West\nGermany", family= label_family) +
  annotate(geom = "text", x = 2008, y = 30, label = "Australia", family= label_family) +
  annotate(geom = "text", x = 1980, y = 28, label = "Poland", family= label_family) +
  annotate(geom = "text", x = 2012, y = 28, label = "Russia", family = label_family, color = "white") + 
  annotate(geom  = "segment", x = 1982.02, xend = 1985.98, y = 13, yend = 13, size = 1.15) +
  annotate(geom  = "segment", x = 1994.02, xend = 1997.98, y = 22, yend = 22, size = 1.15) +
    annotate(geom  = "segment", x = 1998.02, xend = 2001.98, y = 8.5, yend = 8.5, size = 1.15) +
      annotate(geom  = "segment", x = 2006.02, xend = 2009.98, y = 18.5, yend = 18.5, size = 1.15) +
  paralympics_theme

p
```


```{r}
ggsave(plot = p, filename = "paralympics.png", device = "png", units = "in", width = 4, height = 2.25, scale = 2, type = "cairo")
```




```{r}
sessionInfo()
```


